# Generated by Django 3.1.7 on 2021-05-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0005_transpotextdec_transpotextenc'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigtextenc',
            name='key',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vigtextenc',
            name='ciphertext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vigtextenc',
            name='plaintext',
            field=models.TextField(default=''),
        ),
    ]
