# Generated by Django 3.1.7 on 2021-05-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0006_auto_20210529_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigtextenc',
            name='description',
            field=models.TextField(default='Vigenere Text Encryption'),
        ),
    ]
