# Generated by Django 3.1.7 on 2021-05-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0007_vigtextenc_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigtextdec',
            name='description',
            field=models.TextField(default='Vigenere Text Decryption'),
        ),
        migrations.AddField(
            model_name='vigtextdec',
            name='key',
            field=models.TextField(default=''),
        ),
    ]
