# Generated by Django 3.2.3 on 2021-05-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0008_auto_20210529_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='transpotextdec',
            name='description',
            field=models.TextField(default='Transposition Text Decryption'),
        ),
        migrations.AddField(
            model_name='transpotextdec',
            name='key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='transpotextenc',
            name='description',
            field=models.TextField(default='Transposition Text Encryption'),
        ),
        migrations.AddField(
            model_name='transpotextenc',
            name='key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vertextdec',
            name='description',
            field=models.TextField(default='Vernam Text Decryption'),
        ),
        migrations.AddField(
            model_name='vertextenc',
            name='description',
            field=models.TextField(default='Vernam Text Encryption'),
        ),
        migrations.AddField(
            model_name='vigfileenc',
            name='description',
            field=models.TextField(default='Vigenere File Encryption'),
        ),
        migrations.AlterField(
            model_name='transpotextdec',
            name='ciphertext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transpotextdec',
            name='plaintext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transpotextenc',
            name='ciphertext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transpotextenc',
            name='plaintext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vertextdec',
            name='ciphertext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vertextdec',
            name='plaintext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vertextenc',
            name='ciphertext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vertextenc',
            name='plaintext',
            field=models.TextField(default=''),
        ),
    ]
