# Generated by Django 3.2.3 on 2021-05-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0010_owntextdec_owntextenc'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigfileenc',
            name='key',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vigfileenc',
            name='ciphertext',
            field=models.FileField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='vigfileenc',
            name='plaintext',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
