# Generated by Django 3.2.3 on 2021-05-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0015_auto_20210531_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verfileenc',
            name='ciphertext',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
