# Generated by Django 3.2.3 on 2021-05-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0016_alter_verfileenc_ciphertext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verfileenc',
            name='ciphertext',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
