# Generated by Django 3.2.3 on 2021-05-31 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SecApp', '0018_verfileenc_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigfiledec',
            name='ext',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vigfileenc',
            name='ext',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verfileenc',
            name='ext',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='verfileenc',
            name='plaintext',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vigfiledec',
            name='ciphertext',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vigfiledec',
            name='key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vigfiledec',
            name='plaintext',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vigfileenc',
            name='ciphertext',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vigfileenc',
            name='key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vigfileenc',
            name='plaintext',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='VerFileDec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintext', models.FileField(blank=True, upload_to='')),
                ('ciphertext', models.FileField(blank=True, upload_to='')),
                ('description', models.TextField(default='Vernam File Decryption')),
                ('ext', models.CharField(default='', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranspoFileEnc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintext', models.FileField(blank=True, upload_to='')),
                ('ciphertext', models.FileField(blank=True, upload_to='')),
                ('description', models.TextField(default='Transposition File Encryption')),
                ('ext', models.CharField(default='', max_length=10)),
                ('key', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranspoFileDec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintext', models.FileField(blank=True, upload_to='')),
                ('ciphertext', models.FileField(blank=True, upload_to='')),
                ('description', models.TextField(default='Transposition File Decryption')),
                ('ext', models.CharField(default='', max_length=10)),
                ('key', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnFileEnc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintext', models.FileField(blank=True, upload_to='')),
                ('ciphertext', models.FileField(blank=True, upload_to='')),
                ('description', models.TextField(default='J&A Homebrew File Encryption')),
                ('ext', models.CharField(default='', max_length=10)),
                ('key', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnFileDec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintext', models.FileField(blank=True, upload_to='')),
                ('ciphertext', models.FileField(blank=True, upload_to='')),
                ('description', models.TextField(default='J&A Homebrew File Decryption')),
                ('ext', models.CharField(default='', max_length=10)),
                ('key', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
