# Generated by Django 3.2.3 on 2021-05-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0020_alter_verfileenc_ciphertext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownfiledec',
            name='plaintext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ownfileenc',
            name='ciphertext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transpofiledec',
            name='plaintext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transpofileenc',
            name='ciphertext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='verfiledec',
            name='plaintext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vigfiledec',
            name='plaintext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vigfileenc',
            name='ciphertext',
            field=models.TextField(default=''),
        ),
    ]
