# Generated by Django 3.2.3 on 2021-05-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0022_auto_20210531_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vigfileenc',
            name='ciphertext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vigfileenc',
            name='plaintext',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
